obj-$(CONFIG_USB_DESIGN_WARE)	+= dwc_otg_driver.o \
				   dwc_otg_cil.o \
				   dwc_otg_pcd.o \
				   dwc_otg_hcd.o \
				   dwc_otg_adp.o \
				   dwc_common_linux.o \
				   dwc_otg_cil_intr.o \
				   dwc_otg_pcd_intr.o \
				   dwc_otg_hcd_ddma.o \
				   dwc_otg_hcd_queue.o \
				   dwc_otg_hcd_intr.o \
				   dwc_otg_pcd_linux.o \
				   dwc_otg_hcd_linux.o \
				   dwc_otg_attr.o
